services:

  nginx:
    image: nginx:1.28.2
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-service
      - map-service
      - login-front
      - map-front

  login-front:
    container_name: login-frontend-service
    build:
      context: ../buried-marks-frontend-microservice/services/login_front
      dockerfile: Dockerfile
    expose:
      - "8080"
    restart: always

  map-front:
    container_name: map-frontend-service
    build:
      context: ../buried-marks-frontend-microservice/services/map_front
      dockerfile: Dockerfile
    expose:
      - "8080"
    restart: always

  auth-db:
    image: postgres:18-alpine
    container_name: auth_postgres
    env_file:
      - ../buried-marks-authentication-microservice/.env
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  auth-service:
    build:
      context: ../buried-marks-authentication-microservice
      dockerfile: Dockerfile
    env_file:
      - ../buried-marks-authentication-microservice/.env
    environment:
      DB_HOST: auth-db
    expose:
      - "8000"
    depends_on:
      -   auth-db

  map-service-db:
    container_name: buried-marks-map-service-db
    env_file:
      - ../buried-marks-map-microservice/.env
    image: mariadb:11.4-noble
    restart: always
    expose:
      - "3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5

  map-service:
    build:
      context: ../buried-marks-map-microservice
      dockerfile: Dockerfile
    env_file:
      - ../buried-marks-map-microservice/.env
    expose:
      - "9001"
    environment:
      DATABASE_HOST: map-service-db
    depends_on:
      map-service-db:
        condition: service_healthy

  valkey:
    image: valkey/valkey:9-alpine
    container_name: valkey_db
    volumes:
      - valkey_data:/data

  mail_service:
    build:
      context: ../buried-marks-mail-microservice
      dockerfile: Dockerfile
    container_name: mail_worker
    env_file:
      - ../buried-marks-mail-microservice/.env
    depends_on:
      - valkey

  voting-service:
    container_name: voting-service
    build:
      context: ../buried-marks-voting-microservice
      dockerfile: Dockerfile
    command: >
      bash -c "python app/backend_pre_start.py &&
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8900 --reload"
    volumes:
      - ../buried-marks-voting-microservice:/app
    env_file:
      - ../buried-marks-voting-microservice/.env
    expose:
      - "8900"
    depends_on:
      - voting-db  
    restart: always

  voting-db:
    container_name: voting_db
    image: postgres:alpine
    env_file:
      - ../buried-marks-voting-microservice/.env
    expose:
      - "5432"
    volumes:
      - voting_db_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
  valkey_data:
  voting_db_data: