server {
    listen 80;

    location /api/login/ {
        proxy_pass http://auth-service:8000;
    }

    location /api/token/ {
        proxy_pass http://auth-service:8000;
    }

    location /api/update-password/ {
        proxy_pass http://auth-service:8000;
    }

    location /api/markers/ {
        proxy_pass http://map-service:9001;
    }

    location /api/categories/ {
        proxy_pass http://map-service:9001;
    }

    location /map/ {
        proxy_pass http://map-front:8080/;
    }

    location / {
        proxy_pass http://login-front:8080;
    }

}
